name: Build Image

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  IMAGE_PATH: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}-image

jobs:

  push_image:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    # Build a docker image and push to registry.
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup docker builder
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Log into GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: |
            ${{ env.IMAGE_PATH }}
